#!/bin/bash
# Blocks hand-edits to generated files. Exit 2 = blocking error.

INPUT=$(cat)
FILE=$(printf '%s' "$INPUT" | jq -r '.tool_input.file_path // empty')
[ -n "$FILE" ] || exit 0

case "$FILE" in
  *shield_data.db)
    echo "Blocked: $FILE is a generated SQLite artifact. Rebuild it with 'python src/shield_data/build_db.py' instead of editing it." >&2
    exit 2
    ;;
  *_version.py)
    echo "Blocked: $FILE is generated by setuptools-scm. Version comes from git tags; do not edit it." >&2
    exit 2
    ;;
esac

exit 0
